package com.furybook.dubl.model

/** Generated from the validated DUBL 3.69 rulebook bundle. Do not edit by hand. */
internal object GeneratedSkillCatalog {
    val rankCosts: List<Int> = listOf(0, 10, 30, 60, 100, 150, 210, 280, 360, 450, 550)

    val definitions: List<SkillDefinition> = listOf(
        SkillDefinition(
            id = "athletics",
            name = "Атлетика",
            description = "Прыжки, лазание, плавание",
            category = SkillCategory.PHYSICAL,
            defaultAttribute = AttributeId.STRENGTH,
            untrained = UntrainedRule.YES,
            auto6 = "Да",
            auto12 = "Нет",
            template = false,
        ),
        SkillDefinition(
            id = "barter",
            name = "Бартер",
            description = "Торговля,",
            category = SkillCategory.SOCIAL,
            defaultAttribute = AttributeId.CHARISMA,
            untrained = UntrainedRule.YES,
            auto6 = "Нет",
            auto12 = "Нет",
            template = false,
        ),
        SkillDefinition(
            id = "awareness",
            name = "Внимательность",
            description = "Слух, зрение",
            category = SkillCategory.FIELD,
            defaultAttribute = AttributeId.PERCEPTION,
            untrained = UntrainedRule.YES,
            auto6 = "Да",
            auto12 = "Нет",
            template = false,
        ),
        SkillDefinition(
            id = "riding",
            name = "Верховая езда",
            description = "Держаться в седле",
            category = SkillCategory.PHYSICAL,
            defaultAttribute = AttributeId.DEXTERITY,
            untrained = UntrainedRule.YES_MINUS_2,
            auto6 = "Нет",
            auto12 = "Нет",
            template = false,
        ),
        SkillDefinition(
            id = "lockpicking",
            name = "Взлом",
            description = "Взламывание замков и схожих устройств",
            category = SkillCategory.TECHNICAL,
            defaultAttribute = AttributeId.DEXTERITY,
            untrained = UntrainedRule.YES,
            auto6 = "Да",
            auto12 = "Да",
            template = false,
        ),
        SkillDefinition(
            id = "driving",
            name = "Вождение",
            description = "Управление колесным транспортом",
            category = SkillCategory.TECHNICAL,
            defaultAttribute = AttributeId.DEXTERITY,
            untrained = UntrainedRule.YES_MINUS_2,
            auto6 = "Нет",
            auto12 = "Нет",
            template = false,
        ),
        SkillDefinition(
            id = "survival",
            name = "Выживание",
            description = "Охота, ориентирование в дикой местности",
            category = SkillCategory.FIELD,
            defaultAttribute = AttributeId.PERCEPTION,
            untrained = UntrainedRule.YES_MINUS_2,
            auto6 = "Нет",
            auto12 = "Нет",
            template = false,
        ),
        SkillDefinition(
            id = "animal_handling",
            name = "Дрессировка",
            description = "",
            category = SkillCategory.SOCIAL,
            defaultAttribute = AttributeId.CHARISMA,
            untrained = UntrainedRule.NO,
            auto6 = "Да",
            auto12 = "Нет",
            template = false,
        ),
        SkillDefinition(
            id = "intimidation",
            name = "Запугивание",
            description = "Устрашение",
            category = SkillCategory.SOCIAL,
            defaultAttribute = AttributeId.CHARISMA,
            untrained = UntrainedRule.YES,
            auto6 = "Нет",
            auto12 = "Нет",
            template = false,
        ),
        SkillDefinition(
            id = "knowledge_academic",
            name = "Знание (Академическое)",
            description = "",
            category = SkillCategory.KNOWLEDGE,
            defaultAttribute = AttributeId.INTELLIGENCE,
            untrained = UntrainedRule.YES,
            auto6 = "Нет",
            auto12 = "Нет",
            template = false,
        ),
        SkillDefinition(
            id = "knowledge_template",
            name = "Знание (Любое)",
            description = "",
            category = SkillCategory.KNOWLEDGE,
            defaultAttribute = AttributeId.INTELLIGENCE,
            untrained = UntrainedRule.NO,
            auto6 = "Нет",
            auto12 = "Нет",
            template = true,
        ),
        SkillDefinition(
            id = "engineering_repair",
            name = "Инженерное дело (Ремонт)",
            description = "",
            category = SkillCategory.TECHNICAL,
            defaultAttribute = AttributeId.INTELLIGENCE,
            untrained = UntrainedRule.NO,
            auto6 = "Да",
            auto12 = "Нет",
            template = false,
        ),
        SkillDefinition(
            id = "performance_vocal",
            name = "Исполнение (Вокал)",
            description = "Пение",
            category = SkillCategory.SOCIAL,
            defaultAttribute = AttributeId.CHARISMA,
            untrained = UntrainedRule.YES_MINUS_2,
            auto6 = "Нет",
            auto12 = "Нет",
            template = false,
        ),
        SkillDefinition(
            id = "performance_template",
            name = "Исполнение (Любое)",
            description = "Игра на музыкальных инструментах, ораторское искусство, танцы",
            category = SkillCategory.SOCIAL,
            defaultAttribute = AttributeId.CHARISMA,
            untrained = UntrainedRule.NO,
            auto6 = "Нет",
            auto12 = "Нет",
            template = true,
        ),
        SkillDefinition(
            id = "leadership",
            name = "Лидерство",
            description = "Управление подчиненными, командование",
            category = SkillCategory.SOCIAL,
            defaultAttribute = AttributeId.CHARISMA,
            untrained = UntrainedRule.YES,
            auto6 = "Нет",
            auto12 = "Нет",
            template = false,
        ),
        SkillDefinition(
            id = "eloquence",
            name = "Красноречие",
            description = "Обман, дипломатия",
            category = SkillCategory.SOCIAL,
            defaultAttribute = AttributeId.CHARISMA,
            untrained = UntrainedRule.YES,
            auto6 = "Нет",
            auto12 = "Нет",
            template = false,
        ),
        SkillDefinition(
            id = "medicine",
            name = "Медицина",
            description = "Оказание медицинской помощи",
            category = SkillCategory.KNOWLEDGE,
            defaultAttribute = AttributeId.INTELLIGENCE,
            untrained = UntrainedRule.YES,
            auto6 = "Нет",
            auto12 = "Нет",
            template = false,
        ),
        SkillDefinition(
            id = "piloting",
            name = "Пилотирование",
            description = "Управление летательными аппаратами,",
            category = SkillCategory.TECHNICAL,
            defaultAttribute = AttributeId.DEXTERITY,
            untrained = UntrainedRule.NO,
            auto6 = "Нет",
            auto12 = "Нет",
            template = false,
        ),
        SkillDefinition(
            id = "search",
            name = "Поиск",
            description = "",
            category = SkillCategory.FIELD,
            defaultAttribute = AttributeId.PERCEPTION,
            untrained = UntrainedRule.YES,
            auto6 = "Да",
            auto12 = "Да",
            template = false,
        ),
        SkillDefinition(
            id = "profession_template",
            name = "Профессия",
            description = "",
            category = SkillCategory.KNOWLEDGE,
            defaultAttribute = AttributeId.INTELLIGENCE,
            untrained = UntrainedRule.NO,
            auto6 = "Да",
            auto12 = "Нет",
            template = true,
        ),
        SkillDefinition(
            id = "craft_template",
            name = "Ремесло",
            description = "Создание предметов",
            category = SkillCategory.TECHNICAL,
            defaultAttribute = AttributeId.INTELLIGENCE,
            untrained = UntrainedRule.NO,
            auto6 = "Да",
            auto12 = "Да",
            template = true,
        ),
        SkillDefinition(
            id = "stealth",
            name = "Скрытность",
            description = "Незаметность, бесшумность",
            category = SkillCategory.FIELD,
            defaultAttribute = AttributeId.DEXTERITY,
            untrained = UntrainedRule.YES,
            auto6 = "Нет",
            auto12 = "Нет",
            template = false,
        ),
        SkillDefinition(
            id = "shooting",
            name = "Стрельба",
            description = "Меткость и точность стрельбы",
            category = SkillCategory.COMBAT,
            defaultAttribute = AttributeId.PERCEPTION,
            untrained = UntrainedRule.YES,
            auto6 = "Нет",
            auto12 = "Нет",
            template = false,
        ),
        SkillDefinition(
            id = "melee_weapon",
            name = "Холодное оружие",
            description = "Опытность владения холодным оружием, точность атак",
            category = SkillCategory.COMBAT,
            defaultAttribute = AttributeId.DEXTERITY,
            untrained = UntrainedRule.YES,
            auto6 = "Нет",
            auto12 = "Нет",
            template = false,
        ),
        SkillDefinition(
            id = "throwing",
            name = "Метание",
            description = "Меткость и точность метания",
            category = SkillCategory.COMBAT,
            defaultAttribute = AttributeId.DEXTERITY,
            untrained = UntrainedRule.YES,
            auto6 = "Нет",
            auto12 = "Нет",
            template = false,
        ),
        SkillDefinition(
            id = "unarmed",
            name = "Рукопашный бой",
            description = "Кулачные бои, борьба",
            category = SkillCategory.COMBAT,
            defaultAttribute = AttributeId.DEXTERITY,
            untrained = UntrainedRule.YES,
            auto6 = "Нет",
            auto12 = "Нет",
            template = false,
        ),
        SkillDefinition(
            id = "computers",
            name = "Компьютеры",
            description = "",
            category = SkillCategory.TECHNICAL,
            defaultAttribute = AttributeId.INTELLIGENCE,
            untrained = UntrainedRule.UNSPECIFIED,
            auto6 = "Не указано в базовой таблице",
            auto12 = "Не указано в базовой таблице",
            template = false,
        ),
    )
}
